# This is a basic workflow to help you get started with Actions

name: Scheduled run

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:
  schedule:
    - cron: '30 15 * * 1,3,5'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # 1.Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: pull code from remote repository
        uses: actions/checkout@v4

      # 2.Install Node.js
      - name: setup Node.js
        uses: actions/setup-node@v4

      # 3.Install Newman & Reporter
      - name: Install Newman & Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      
      - name: Run Postman
        run: 'newman run Trello_Anna.postman_collection.json -e Trello_Environment.postman_environment.json -r cli,htmlextra --reporter-htmlextra-export report.html'
   
      # 5. Check htmlextra
      - name: Check htmlextra
        run: ls   
